language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
services:
- elasticsearch
- mongodb
install:
- pip install pep8
- pip install pyflakes
- pip install coveralls
- pip install jsonpickle
- pip install pymongo elasticsearch
- pip freeze
- python setup.py install
before_script:
- pyflakes libnessus/*.py
- sleep 10
script: nosetests --with-coverage --cover-package=libnessus
after_script:
- curl -XDELETE localhost:9200/nessus_reports
after_success: coveralls
deploy:
  provider: pypi
  user: Michael.Boutillier
  password:
    secure: GzFRAdLGSG0SYHzwSY/G1G3j+MqLLXineFEvMZYtlDfhRnGfFr9WdOiK/2NbGz0Uj6pF1iPj1ojZdKyn0INOuOyjICGQDzZCVky5gonCl8ZmulUqn1dwHGkNw5zlzfrrAz2ojjFmpE2W34j5NAUrEdfyLR9+nmtrpexAhLHRhbs=
  on:
    tags: true
    repo: bmx0r/python-libnessus
