language: python
python:
  - "2.6"
  - "2.7"
#  - "3.2" Not ready yet
# command to install dependencies

install:
  - "pip install pep8 --use-mirrors"
  - "pip install pyflakes --use-mirrors"
  - "pip install coveralls"
  - "pip install jsonpickle"
  - "python setup.py install"
before_script:
  - "pep8 . --exclude test,docs,examples"
  - "pyflakes ."
script: 
  nosetests --with-coverage --cover-package=libnessus
after_success:
  coveralls
